// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfResourceGantt.ProjectManagement.Data;

#nullable disable

namespace WpfResourceGantt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312000000_AddRowVersionConcurrency")]
    partial class AddRowVersionConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.AdminTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminTasks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.EvmWeeklySnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double>("ACWP")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "acwp");

                    b.Property<decimal>("BAC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "bac");

                    b.Property<double>("BCWP")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "bcwp");

                    b.Property<double>("BCWS")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "bcws");

                    b.Property<double>("CPI")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "cpi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdByUserId");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isLocked");

                    b.Property<double>("Progress")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "progress");

                    b.Property<double>("SPI")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "spi");

                    b.Property<string>("SubProjectId")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "subProjectId");

                    b.Property<DateTime>("WeekEndingDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "weekEndingDate");

                    b.HasKey("Id");

                    b.HasIndex("SubProjectId", "WeekEndingDate")
                        .IsUnique()
                        .HasFilter("[SubProjectId] IS NOT NULL");

                    b.ToTable("EvmWeeklySnapshots");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressBlock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isCompleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("WorkItemId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ProgressBlocks");

                    b.HasAnnotation("Relational:JsonPropertyName", "progressBlocks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressHistoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double>("ActualProgress")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "actualProgress");

                    b.Property<double?>("ActualWork")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "actualWork");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<double>("ExpectedProgress")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "expectedProgress");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WorkItemId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ProgressHistory");

                    b.HasAnnotation("Relational:JsonPropertyName", "progressHistory");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isCompleted");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("ProgressBlockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgressBlockId");

                    b.ToTable("ProgressItems");

                    b.HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ResourceAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("DeveloperId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "developerId");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "workItemId");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ResourceAssignments");

                    b.HasAnnotation("Relational:JsonPropertyName", "assignments");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.SystemItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("WbsValue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "wbsValue");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.ProjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateGate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predecessors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTemplateId");

                    b.ToTable("TemplateGates");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateGateId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateGateId");

                    b.HasIndex("TemplateTaskId");

                    b.ToTable("TemplateProgressBlocks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateProgressBlockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateProgressBlockId");

                    b.ToTable("TemplateProgressItems");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Predecessors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TemplateGateId")
                        .HasColumnType("int");

                    b.Property<double>("WorkHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TemplateGateId");

                    b.ToTable("TemplateTasks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "hourlyRate");

                    b.Property<string>("ManagedProjectIds")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "managedProjectIds");

                    b.Property<string>("ManagedProjectManagerIds")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "managedProjectManagerIds");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "section");

                    b.Property<double>("WeeklyCapacity")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "weeklyCapacity");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "actualFinishDate");

                    b.Property<double?>("ActualWork")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "actualWork");

                    b.Property<double?>("Acwp")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "acwp");

                    b.Property<string>("AssignedDeveloperId")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "assignedDeveloperId");

                    b.Property<decimal?>("BAC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "bac");

                    b.Property<DateTime?>("BaselineEndDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "baselineEndDate");

                    b.Property<DateTime?>("BaselineStartDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "baselineStartDate");

                    b.Property<double?>("Bcwp")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "bcwp");

                    b.Property<double?>("Bcws")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "bcws");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "durationDays");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "endDate");

                    b.Property<bool>("IsBaselined")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "isBaselined");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverAllocated")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAcwpImportDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "lastAcwpImportDate");

                    b.Property<string>("LastAcwpImportSource")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "lastAcwpImportSource");

                    b.Property<DateTime?>("LateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Predecessors")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "predecessors");

                    b.Property<double>("Progress")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "progress");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ScheduleMode")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "scheduleMode");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "startDate");

                    b.Property<DateTime?>("StartNoEarlierThan")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "startNoEarlierThan");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("SystemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalFloat")
                        .HasColumnType("int");

                    b.Property<string>("WbsValue")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "wbsValue");

                    b.Property<double?>("Work")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "work");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SystemId");

                    b.ToTable("WorkItems");

                    b.HasAnnotation("Relational:JsonPropertyName", "children");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressBlock", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", null)
                        .WithMany("ProgressBlocks")
                        .HasForeignKey("WorkItemId");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressHistoryItem", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", null)
                        .WithMany("ProgressHistory")
                        .HasForeignKey("WorkItemId");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressItem", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.ProgressBlock", null)
                        .WithMany("Items")
                        .HasForeignKey("ProgressBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ResourceAssignment", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", null)
                        .WithMany("Assignments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateGate", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.Templates.ProjectTemplate", "ProjectTemplate")
                        .WithMany("Gates")
                        .HasForeignKey("ProjectTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTemplate");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressBlock", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateGate", "TemplateGate")
                        .WithMany("Blocks")
                        .HasForeignKey("TemplateGateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateTask", null)
                        .WithMany("Blocks")
                        .HasForeignKey("TemplateTaskId");

                    b.Navigation("TemplateGate");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressItem", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressBlock", "TemplateProgressBlock")
                        .WithMany("Items")
                        .HasForeignKey("TemplateProgressBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateProgressBlock");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateTask", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateGate", "TemplateGate")
                        .WithMany("Tasks")
                        .HasForeignKey("TemplateGateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateGate");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", b =>
                {
                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WpfResourceGantt.ProjectManagement.Models.SystemItem", null)
                        .WithMany("Children")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.ProgressBlock", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.SystemItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.ProjectTemplate", b =>
                {
                    b.Navigation("Gates");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateGate", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateProgressBlock", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.Templates.TemplateTask", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("WpfResourceGantt.ProjectManagement.Models.WorkBreakdownItem", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");

                    b.Navigation("ProgressBlocks");

                    b.Navigation("ProgressHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
